import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import Input from "../../components/Inputs/Input";
import { createSessionFromForm } from "../../services/sessionService";

const CreateSessionForm = ({ onCreated }) => {
  const [formData, setFormData] = useState({
    role: "",
    experience: "",
    topicsToFocus: "",
    description: "",
  });

  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const navigate = useNavigate();

  const handleChange = (key, value) => {
    setFormData((prevData) => ({
      ...prevData,
      [key]: value,
    }));
  };

  const handleCreateSession = async (e) => {
    e.preventDefault();
    const { role, experience, topicsToFocus, description } = formData;

    if (!role || !experience || !topicsToFocus || !description) {
      setError("Please fill in all fields.");
      return;
    }
    setError("");
    setIsLoading(true);

    try {
      const session = await createSessionFromForm(formData);
      onCreated?.(session);
      navigate(`/interview-prep/${session._id}`);
    } catch (err) {
      const msg =
        err.response?.data?.message ||
        err.message ||
        "Something went wrong. Please try again.";
      setError(msg);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="w-full max-w-full mx-auto text-center sm:text-left">
      <p className="text-sm text-gray-600 leading-relaxed mb-6 max-w-md mx-auto sm:mx-0">
        Mock mode creates sample questions instantly. With the API connected,
        questions are generated by AI from your answers below.
      </p>

      <form
        className="flex flex-col gap-5 w-full max-w-full"
        onSubmit={handleCreateSession}
      >
        <Input
          label="Role"
          placeholder="e.g., Backend Engineer"
          type="text"
          value={formData.role}
          onChange={(e) => handleChange("role", e.target.value)}
        />
        <Input
          label="Experience (years)"
          placeholder="e.g., 4"
          type="number"
          value={formData.experience}
          onChange={(e) => handleChange("experience", e.target.value)}
        />
        <Input
          label="Topics to focus on"
          placeholder="e.g., APIs, PostgreSQL, caching"
          type="text"
          value={formData.topicsToFocus}
          onChange={(e) => handleChange("topicsToFocus", e.target.value)}
        />
        <div className="w-full min-w-0 text-left">
          <label className="block text-[13px] font-medium text-slate-700 mb-1.5">
            Additional details
          </label>
          <textarea
            value={formData.description}
            onChange={(e) => handleChange("description", e.target.value)}
            placeholder="What should we emphasize? Team size, stack, interview stage…"
            rows={3}
            className="w-full min-w-0 rounded-xl border border-gray-200/90 bg-white px-4 py-3 text-sm text-gray-900 placeholder:text-gray-400 outline-none transition-shadow focus:border-orange-400 focus:ring-2 focus:ring-orange-100/80 resize-y min-h-[88px]"
          />
        </div>

        {error && (
          <p
            className="text-sm text-red-600 text-center sm:text-left bg-red-50 border border-red-100 rounded-xl px-3 py-2.5"
            role="alert"
          >
            {error}
          </p>
        )}

        <button
          className="btn-primary w-full mt-1"
          type="submit"
          disabled={isLoading}
        >
          {isLoading ? "Creating session…" : "Create session"}
        </button>
      </form>
    </div>
  );
};

export default CreateSessionForm;
